name: asigna
channels:
  - plotly
  - gurobi
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - arrow-cpp=19.0.0
  - arviz=0.17.1
  - asttokens=2.4.1
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - binutils_impl_win-64=2.43
  - binutils_win-64=2.43
  - blas=1.0
  - bokeh=3.4.3
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cloudpickle=3.0.0
  - cmdstan=2.33.1
  - colorama=0.4.6
  - comm=0.2.2
  - cython=3.1.1
  - cytoolz=1.0.1
  - dask=2024.5.0
  - dask-core=2024.5.0
  - dask-expr=1.1.0
  - debugpy=1.8.5
  - decorator=5.1.1
  - distributed=2024.5.0
  - distutils-activate-mingw=2.3
  - ecos=2.0.12
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glog=0.5.0
  - glpk=5.0
  - gurobi=12.0.1
  - h5netcdf=1.6.1
  - h5py=3.12.1
  - hdf5=1.14.5
  - heapdict=1.0.1
  - icc_rt=2022.1.0
  - idna=3.7
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - importlib_resources=6.4.0
  - intel-openmp=2021.4.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipywidgets=8.1.7
  - jedi=0.19.1
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.15
  - krb5=1.21.3
  - lcms2=2.12
  - ld_impl_win-64=2.43
  - lerc=3.0
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libdeflate=1.17
  - libevent=2.1.12
  - libgcc-devel_win-64=13.3.0
  - libgrpc=1.71.0
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libpython=2.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-devel_win-64=13.3.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - m2-bash=4.3.042
  - m2-coreutils=8.25
  - m2-filesystem=2016.04
  - m2-gcc-libs=5.3.0
  - m2-gmp=6.1.0
  - m2-libiconv=1.14
  - m2-libintl=0.19.7
  - m2-make=4.1
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-sed=4.2.2
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-sysroot_win-64=12.0.0.r4.gg4f2fc60ca
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.5.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mingw-w64-ucrt-x86_64-crt-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-headers-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-windows-default-manifest=6.4
  - mingw-w64-ucrt-x86_64-winpthreads-git=12.0.0.r4.gg4f2fc60ca
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.3
  - msys2-conda-epoch=20160418
  - narwhals=1.40.0
  - nest-asyncio=1.6.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.5.0
  - orc=2.1.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - partd=1.4.2
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=4.2.2
  - plotly=6.0.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python-lmdb=1.6.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2024.1
  - pywin32=306
  - pyyaml=6.0.2
  - pyzmq=26.1.1
  - re2=2024.07.02
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.10.1
  - seaborn=0.13.2
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2022.0.0
  - tblib=1.7.0
  - threadpoolctl=3.5.0
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.43.0
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - xarray=2024.7.0
  - xarray-einstats=0.7.0
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.20.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cmdstanpy==1.2.5
      - contourpy==1.2.1
      - convertdate==2.4.0
      - cycler==0.12.1
      - ephem==4.2
      - fonttools==4.53.1
      - highspy==1.9.0
      - holidays==0.73
      - importlib-resources==6.4.4
      - kiwisolver==1.4.5
      - lunarcalendar==0.0.9
      - networkx==3.2.1
      - ply==3.11
      - prophet==1.1.6
      - pyarrow==19.0.1
      - pymeeus==0.5.12
      - pyomo==6.9.2
      - pyparsing==3.1.4
      - pystan==2.19.1.1
      - stanio==0.5.1
      - tsam==2.3.6
      - tzdata==2024.1
prefix: C:\Users\oarenas\AppData\Local\miniconda3\envs\asigna
